services:
  timesheet-api:
    build: .
    ports:
      - "5000:80"
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=TimeSheetManagement;User=sa;Password=${SA_PASSWORD};"
      Jwt__Key: "${JWT_KEY}"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: timesheet-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "1433:1433"
